name: build fonts
on:
  push:
    branches:
      - master
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      # - name: Run Git LFS
      #   run: git lfs install
      # - name: Install Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: latest

      - name: Install NPM
        uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f
        with:
          node-version: 24
          cache: npm

      - name: Install ttfautohint (Linux)
        uses:  awalsh128/cache-apt-pkgs-action@acb598e5ddbc6f68a970c5da0688d2f3a9f04d05
        with:
          packages: ttfautohint

      - name: Build Font
        run: |
          npm install
          npm run --silent build -- ttf::"$NAME"
          tar -C dist/"$NAME" -I 'zstd -T0 -19' -cf "$NAME".tar.zst .
        env:
          NAME: ${{ matrix.font-name }}

      - name: Upload Artifact
        uses: actions/upload-artifact@bbbca2ddaa5d8feaa63e36b76fdaad77386f024f
        with:
          path: "${{ matrix.font-name }}.tar.zst"
          if-no-files-found: error
          retention-days: 90
          archive: false


    strategy:
      # max-parallel: 1
      fail-fast: false
      matrix:
        font-name: ["lj-iosevka-term", "lj-iosevka-fcmono", "lj-iosevka-aile", "lj-iosevka-etoile"]

