name: build fonts
on:
  push:
    branches:
      - master
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8

      # - name: Run Git LFS
      #   run: git lfs install
      # - name: Install Node.js
      #   uses: actions/setup-node@v3
      #   with:
      #     node-version: latest

      - name: Install NPM
        uses: actions/setup-node@395ad3262231945c25e8478fd5baf05154b1d79f

      - name: Install ttfautohint
        uses:  awalsh128/cache-apt-pkgs-action@acb598e5ddbc6f68a970c5da0688d2f3a9f04d05
        with:
          packages: ttfautohint

      - name: Build Font
        run: |
          npm install
          npm run --silent build -- ttf::${{ matrix.font-name }}

      - name: Upload Artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f
        with:
          name: "${{ matrix.font-name }}"
          path: "dist/${{ matrix.font-name }}"
          if-no-files-found: error
          retention-days: 90
          compression-level: 9


    strategy:
      # max-parallel: 1
      matrix:
        font-name: ["lj-iosevka-term", "lj-iosevka-fcmono", "lj-iosevka-aile", "lj-iosevka-etoile"]

